config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments
  end
  resources :objects_to_sells

  devise_for :users
  root 'welcome#index'

  get 'myobjects' => 'objects_to_sells#myindex'
  get 'myevents' => 'events#myindex'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: {minimum: 2}
  validates :description, presence: true
  validates :price, presence: true, length: {maximum: 5}
  validates :image, file_size: { less_than: 2.megabytes }
  
  belongs_to :user
  has_many :comments, dependent: :destroy

end

app/models/objects_to_sell.rb
class ObjectsToSell < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :name, presence: true, length: {minimum: 2}
  validates :description, presence: true
  validates :price, presence: true, length: {maximum: 5}
  validates :image, file_size: { less_than: 2.megabytes }
  
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :objects_to_sells
  has_many :events
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
    @comment.destroy
    redirect_to event_path(@event)  
  end
  
private
  def comment_params
        params.require(:comment).permit(:user_id, :body)
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :events_owner, only: [:edit, :update, :destroy]

     # add this method                         
    def events_owner
     unless @event.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this Job'
      redirect_to event_path
     end
    end

  respond_to :html
  
  def myindex
    @events = current_user.events
    respond_with(@events)
  end

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = current_user.events.build
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end
    
  def find_event
      # by calling posts in this manner vs. `Post.find_by_id(params[:id])`, we
      # ensure we won't end up with a post belonging to another user
      current_user.event.where(:id => params[:id]).first
    end

    def event_params
      params.require(:event).permit(:title, :description, :start, :end, :location, :price, :image, :remove_image, :image_cache)
    end
end

app/controllers/objects_to_sells_controller.rb
class ObjectsToSellsController < ApplicationController
  before_action :set_objects_to_sell, only: [:show, :edit, :update, :destroy, :objects_owner]
  before_action :authenticate_user!
  before_action :objects_owner, only: [:edit, :update, :destroy]
    
    # add this method                         
    def objects_owner
     unless @objects_to_sell.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this Job'
      redirect_to objects_to_sell_path
     end
    end

  respond_to :html
  
  def myindex
    @objects_to_sells = current_user.objects_to_sells
    respond_with(@objects_to_sells)
  end

  def index
    @objects_to_sells = ObjectsToSell.all
    respond_with(@objects_to_sells)
  end

  def show
    respond_with(@objects_to_sell)
  end

  def new
    @objects_to_sell = current_user.objects_to_sells.build
    respond_with(@objects_to_sell)
  end

  def edit
  end

  def create
    @objects_to_sell = current_user.objects_to_sells.build(objects_to_sell_params)
    @objects_to_sell.save
    respond_with(@objects_to_sell)
  end

  def update
    @objects_to_sell.update(objects_to_sell_params)
    respond_with(@objects_to_sell)
  end

  def destroy
    @objects_to_sell.destroy
    respond_with(@objects_to_sell)
  end

  private
    def set_objects_to_sell
      @objects_to_sell = ObjectsToSell.find(params[:id])
    end
    
  def find_objects_to_sell
      # by calling posts in this manner vs. `Post.find_by_id(params[:id])`, we
      # ensure we won't end up with a post belonging to another user
      current_user.objects_to_sell.where(:id => params[:id]).first
    end

    def objects_to_sell_params
      params.require(:objects_to_sell).permit(:name, :description, :price, :image, :remove_image, :image_cache)
    end
end

app/controllers/users/registrations_controller.rb
# app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # DELETE /resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/objects_to_sells_helper.rb
module ObjectsToSellsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
</p><strong>by: <%= User.find(comment.user_id).email.split('@').first %></strong><p>
<p><%= comment.body %></p>
<p><small><%= time_ago_in_words(comment.created_at) %> ago</small></p>

<p><%= link_to 'Delete', [comment.event,comment], method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %></p>

app/views/comments/_form.html.erb
<%= form_for([@event,@event.comments.build]) do |f| %>
<p>
  <%= f.label :body %> <br>
  <%= f.text_area :body %>
</p>
<br>
<p>
  <%= f.submit%>
</p>
<%end%>

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
 
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
<div class="panel panel-primary">
<div class="panel-heading">SCHEDULE A NEW EVENT</div>
  <div class="panel-body">
    <div class="form-group">
      <%= f.label :title ,class: 'control-label' %><br>
      <%= f.text_field :title ,class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :description ,class: 'control-label'%><br>
      <%= f.text_area :description ,class: 'form-control'%>
    </div>
   
    <div class="row">
      <div class="col-md-6">
      <div class="field">
      <%= f.label :start %><br>
         <div class='input-group date' id='datetimepicker22'>
          <%= f.text_field :start, class:'form-control'%>
           <span class="input-group-addon">
           <span class="glyphicon glyphicon-calendar"></span>
           </span>
         </div>
        </div>
      </div>
      <div class="col-md-6">
      <div class="form-group">
      <%= f.label :location ,class: 'control-label'%><br>
      <%= f.text_field :location ,class: 'form-control'%>
    </div>
    </div>
   </div>
      
     <div class="row">
      <div class="col-md-6">
      <div class="field">
      <%= f.label :end %><br>
         <div class='input-group date' id='datetimepicker22'>
          <%= f.text_field :end, class:'form-control'%>
           <span class="input-group-addon">
           <span class="glyphicon glyphicon-calendar"></span>
           </span>
         </div>
        </div>
      </div>
      <div class="col-md-6">
      <div class="form-group">
      <%= f.label :price ,class: 'control-label'%><br>
      <%= f.text_field :price ,class: 'form-control'%>
    </div>
    </div>
   </div>
      

 <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
      <% if @event.image? %>
    <%= image_tag @event.image.thumb.url %>
    <div>
      <%= label_tag :remove_image do %>
        Remove image
        <%= f.check_box :remove_image %>
      <% end %>
    </div>
    
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>
  
  </div>
</div>
   


<script>
  $(function () {
    $('#datetimepicker1').datetimepicker();
    dateFormat: 'yy-mm-dd hh:mm:ss'
 });
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing Events to attend | <%= link_to 'Add New Event', new_event_path, class: 'btn btn-success'%> </h1>
<br>
<br>


<div class="row">
   <% @events.each do |event| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag(event.image.thumb.url, alt: 'Image') if event.image? %>
      <div class="caption">
        <h3><%= event.title %></h3>
        <p><%= truncate(event.description, :length => 200) %></p>
        <div class="badge badge-info text-block"> 
        <p><%= number_to_currency(event.price) %></p>
        </div>
        <div class="card-footer">
          <small class="text-muted">By: <%= User.find(event.user_id).email.split('@').first %> </small><br>
          <small class="text-muted">Created on: <%= event.created_at.strftime("%Y-%m-%d") %> </small><br>
          <small class="text-muted">Last updated: <%= event.updated_at.strftime("%Y-%m-%d") %> </small><br>
        </div>
        <p>
          <%= link_to 'Show', event, class: 'btn btn-success' %>
          <% if event.user_id == current_user.id %>
          <%= link_to 'Edit', edit_event_path(event), class: 'btn btn-info' %>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/events/myindex.html.erb
<h1>Listing My Events | <%= link_to 'Add New Event', new_event_path, class: 'btn btn-success'%></h1>
<br>
<br>


<div class="row">
   <% @events.each do |event| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag(event.image.thumb.url, alt: 'Image') if event.image? %>
      <div class="caption">
        <h3><%= event.title %></h3>
        <p><%= truncate(event.description, :length => 200) %></p>
        <div class="badge badge-info text-block"> 
        <p><%= number_to_currency(event.price) %></p>
        </div>
        <p>
          <%= link_to 'Show', event, class: 'btn btn-success'%>
          <%= link_to 'Edit', edit_event_path(event), class: 'btn btn-info' %>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/events/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', events_path, class: 'btn btn-danger'%>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@event.image.thumb.url, alt: 'Image') if @event.image? %>


<p>
  <strong>Name:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>
<br>

<h2> <%= @event.comments.count %> Comment(s)</h2>
  
  <%= render @event.comments%>
  <h3> Add a comment: </h3>

  <%= render 'comments/form'%>
<br>

<% if @event.user_id == current_user.id %>
<%= link_to 'Edit', edit_event_path(@event) %>|
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>  
</head>
    <title><%= content_for?(:title) ? yield(:title) : "CaptainForest" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>    
  </div>
 
    <%= link_to 'Captain Forest', root_path , class:'navbar-brand'%> 
 
   
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'Market Place', objects_to_sells_path %></li>
        <li><%= link_to "Events", events_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "My objects", myobjects_path %></li>
        <li><%= link_to "My events", myevents_path %></li>
        <li><%= link_to current_user.email, myobjects_path %></li>
        <li> <%= link_to("Logout", destroy_user_session_path, :method => :delete) %> </li>
              
      <% else %>
        <li> <%= link_to 'Login', new_user_session_path %> </li>
      <% end %>
    </ul>
  </div>
</nav>
    
       <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       
      </div><!--/row-->

   
    </div> <!-- /container -->
 
  </body>
</html>

app/views/objects_to_sells/_form.html.erb
<%= form_for @objects_to_sell, html: { multipart: true } do |f| %>
  <% if @objects_to_sell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@objects_to_sell.errors.count, "error") %> prohibited this objects_to_sell from being saved:</h2>
 
      <ul>
      <% @objects_to_sell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
      <% if @objects_to_sell.image? %>
    <%= image_tag @objects_to_sell.image.thumb.url %>
    <div>
      <%= label_tag :remove_image do %>
        Remove image
        <%= f.check_box :remove_image %>
      <% end %>
    </div>
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objects_to_sells/edit.html.erb
<h1>Editing objects_to_sell</h1>

<%= render 'form' %>

<%= link_to 'Show', @objects_to_sell %> |
<%= link_to 'Back', objects_to_sells_path %>

app/views/objects_to_sells/index.html.erb
<head>
        <title>CV John</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="css/style.css">
        <script src="js/script.js"></script>
    </head>

<h1>Listing Objects to sell | <%= link_to 'Add New Object', new_objects_to_sell_path, class: 'btn btn-success'%> </h1>
<br>
<br>


<div class="row">
   <% @objects_to_sells.each do |objects_to_sell| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag(objects_to_sell.image.thumb.url, alt: 'Image') if objects_to_sell.image? %>
      <div class="caption">
        <h3><%= objects_to_sell.name %></h3>
        <p><%= truncate(objects_to_sell.description, :length => 200) %></p>
        <div class="badge badge-info text-block"> 
        <p><%= number_to_currency(objects_to_sell.price) %></p>
        </div>
        <div class="card-footer">
          <small class="text-muted">By: <%= User.find(objects_to_sell.user_id).email.split('@').first %> </small><br>
          <small class="text-muted">Created on: <%= objects_to_sell.created_at.strftime("%Y-%m-%d") %> </small><br>
          <small class="text-muted">Last updated: <%= objects_to_sell.updated_at.strftime("%Y-%m-%d") %> </small><br>
        </div>
        <p>
          <%= link_to 'Show', objects_to_sell, class: 'btn btn-success' %>
          <% if objects_to_sell.user_id == current_user.id %>
          <%= link_to 'Edit', edit_objects_to_sell_path(objects_to_sell), class: 'btn btn-info' %>
          <%= link_to 'Destroy', objects_to_sell, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/objects_to_sells/myindex.html.erb
<h1>Listing My Objects to sell | <%= link_to 'Add New Object', new_objects_to_sell_path, class: 'btn btn-success'%> </h1>
<br>
<br>


<div class="row">
   <% @objects_to_sells.each do |objects_to_sell| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag(objects_to_sell.image.thumb.url, alt: 'Image') if objects_to_sell.image? %>
      <div class="caption">
        <h3><%= objects_to_sell.name %></h3>
        <p><%= truncate(objects_to_sell.description, :length => 200) %></p>
        <div class="badge badge-info text-block"> 
        <p><%= number_to_currency(objects_to_sell.price) %></p>
        </div>
        <p>
          <%= link_to 'Show', objects_to_sell, class: 'btn btn-success'%>
          <%= link_to 'Edit', edit_objects_to_sell_path(objects_to_sell), class: 'btn btn-info' %>
          <%= link_to 'Destroy', objects_to_sell, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/objects_to_sells/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', objects_to_sells_path %>

app/views/objects_to_sells/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@objects_to_sell.image.thumb.url, alt: 'Image') if @objects_to_sell.image? %>


<p>
  <strong>Name:</strong>
  <%= @objects_to_sell.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @objects_to_sell.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @objects_to_sell.price %>
</p>

<% if @objects_to_sell.user_id == current_user.id %>
<%= link_to 'Edit', edit_objects_to_sell_path(@objects_to_sell) %>|
<% end %>
<%= link_to 'Back', objects_to_sells_path %>

 

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>CV John</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="css/style.css">
        <script src="js/script.js"></script>
    </head>
    
    
    <body>

        <section id="intro" class="intro">       
      <div class="overlay"></div>
      <div class="content">
        <div class="container clearfix">
          <div class="row">
            <div class="col-lg-8 col-md-12 mx-auto">
             <h1>CAPTAIN FOREST &copy;</h1>
              <p class="italic">Everything students could get locally from their community</p>
            </div>
          </div>
        </div>
      </div>
    </section>
        
    </body>

</html>